# label_dict:
#   USp: 0     # class 1
#   CSpu: 1    # class 2

label_dict:
  CSpr: 0
  CSpu: 1
  CSm: 2
  USp: 3
  USo: 4
  USm: 5

roi_dict:
  lat:  377         # Lateral nucleus
  # bl:   216         # Basolateral (basal) nucleus
  # bm:   217         # Basomedial nucleus
  # cen:  [277, 278]  # Central nucleus
  # med:  279         # Medial nucleus
  # pl:   240         # Paralaminar nucleus

  # aaa:  215         # Anterior amygdaloid area
  # coa:  238         # Cortical amygdaloid nucleus
  # cat:  242         # Corticoamygdaloid transition area
  # asta: 295         # Amygdalostriatal transition area
  # aha:  301         # Amygdalohippocampal area
  # ahta: 320         # Amygdalohippocampal transition area

  # nuc: [216, 217, 240, 277, 278, 279, 377]
  # trans: [242, 295, 301, 320]

  # total: [215, 216, 217, 238, 240, 242, 277, 278, 279, 295, 301, 320, 377]

roi_settings:                   # kwargs passed to data.PrepareROIs()
  src: "freesurfer"             # used in conjunction with {project_dir} below
  roi_dir: null                 # use all files with {extension}
  roi_base: "nextbrain"    # folder name within {project_dir}/{src}
  roi_src: "seg."   # ?h.{roi_name}.{extension}
  extension: ".nii.gz"              # generally mgz or nii.gz

general_settings:
  project_dir: "/mnt/d/fMRI/HRA"
  # save_dir: "/mnt/d/fMRI/Development/HRA/derivatives/panic"
  save_dir: /tmp/test_searchlight
  tmp_dir: "~/.joblib_cache"    # stores temp memmaps
  method: LSA                   # or LSS, if you have GLMsingle: use 'lss', 'lsa'
  source: stglm                 # or 'stglm', 'glmsingle'
  standardize: zscore           # best to keep this
  filters: task-HRA
  overwrite: false

fitted_derivative: false

decoding_settings:
  fold_interval: 3              # if not LORO/LOSO, iterate over labels
  n_permutations: 1           # permutations for ROI-decoding/searchlight
  variance_threshold: 1e-12     # avoid flat time series
  permute_both_sets: true       # false: only permute training labels
  permute_within_groups: false  # true: LOSO/LORO set up; see 'outer_cv'
  scoring: balanced_accuracy    # scoring metric for decoder

  parallel:
    n_jobs: 1                   # this one actually parallizes over permutations/batches
    batch_size: 1               # batch size Parallel process
    backend: "loky"             # backend for Parallel process
    prefer: "processes"         # preference for Parallel process
    verbose: 0                  # verbosity of Parallel process
    update_interval: 100        # log progress every N completed searchlights (0 = disable)

  # this field pertains to panic.plugins.PLUGIN_REGISTRY
  # analysis:
  #   name: decoding
  #   permutations: true
  #   higher_is_better: true
  #   args: {}

  # analysis:
  #   name: dimensionality
  #   permutations: false
  #   higher_is_better: true
  #   args:
  #     metric: participation_ratio

  # analysis:
  #   name: cs_us_similarity
  #   output_kind: timeseries
  #   args:
  #     cs_label: CSpu
  #     us_label: USp
  #     metric: cosine

  analysis:
    name: rsa
    permutations: false
    higher_is_better: true
    args:
      metric: correlation
      compare: spearman
      conditions: [CSpr, CSpu, CSm, USp, USo, USm]
      target_model: contingency
      model_rdms:
        contingency:
          matrix:
            - [0, 0.25, 1.00, 0.25, 0.50, 1.00]  # CSpr
            - [0.25, 0, 1.00, 0.50, 0.25, 1.00]  # CSpu
            - [1.00, 1.00, 0, 1.00, 1.00, 0.25]  # CSm
            - [0.25, 0.50, 1.00, 0, 0.25, 1.00]  # USp
            - [0.50, 0.25, 1.00, 0.25, 0, 1.00]  # USo
            - [1.00, 1.00, 0.25, 1.00, 1.00, 0]  # USm
    
  # # CSpr ~ USp     reinforced CS+ should resemble actual threat
  # # CSpu ~ USo     unreinforced CS+ should resemble omitted-US timepoint
  # # CSm  ~ USm     CS− should resemble matched no-threat US timepoint

  # Pipeline settings: DO NOT CHANGE THE HEADER NAMES ('SCALER', 'CV', 'ESTIMATOR', etc)
  # preprocessing | if 'standardize' is null
  scaler:
    name: StandardScaler
    args:
      with_mean: true
      with_std: true

  # outer cv
  outer_cv:
    name: LeaveOneGroupOut
    args: {}

  # select test/training labels
  cv:
    name: StratifiedKFold
    args:
      n_splits: 3
      shuffle: False

  # estimator
  estimator:
    name: SVC
    args:
      C: 1
      kernel: linear
      class_weight: balanced

  # select features (e.g., percentile or SelectKBest)
  feature_selection:
    name: SelectPercentile
    args:
      percentile: 10
      score_func: f_classif

  # grid search
  gridsearch:
    name: GridSearchCV
    args:
      param_grid:
        select__percentile: [10, 20, 40, 100] # see 'feature_selection'
        clf__C: [0.01, 0.1, 1, 10]
      n_jobs: 1               # keep this at 1 to avoid nesting

  # searchlight
  searchlight:
    alpha: 0.05                   # value for FDR correction
    radius_mm: 6                  # radius around center
    target_zooms: null            # downsample data to reduce number of centers; e.g., [2.0, 2.0, 2.0]
    basepath: "searchlight"       # subfolder within {save_dir} to save searchlight results
    locked:                       # disable gridsearch within searchlight
      clf__C: 1.0
